spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Tomaspedro1.
spring.jpa.hibernate.ddl-auto=update






